name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Trigger the workflow only when a tag starting with "v" is pushed (e.g., v0.1.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"  # Specify the Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    # Step 4: Build the package
    - name: Build the package
      run: python -m build

    # Step 5: Publish to PyPI
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
